### ISSUE TITLE
COMMAND undefined, COMM instead

### ISSUE THREAD

**Issue by marwin79** [ioBroker/dev-server#11] opened 2021-03-13 05:58 UTC
https://github.com/ioBroker/dev-server/blob/138c1a662c06bda808c67312f3e1c14825ca7f18/src/index.ts#L472

`
TypeError: Cannot read property 'match' of undefined
    at /usr/local/lib/node_modules/@iobroker/dev-server/dist/index.js:398:59
    at Array.find (<anonymous>)
    at DevServer.waitForNodeChildProcess (/usr/local/lib/node_modules/@iobroker/dev-server/dist/index.js:398:37)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async DevServer.startAdapterDebug (/usr/local/lib/node_modules/@iobroker/dev-server/dist/index.js:391:27)
    at async DevServer.debug (/usr/local/lib/node_modules/@iobroker/dev-server/dist/index.js:170:9)
    at async Object.handler (/usr/local/lib/node_modules/@iobroker/dev-server/dist/index.js:86:28)
`

On my MacOS with nodejs v15.5.1, the object looks like this:

`
[
  {
    PPID: '65302',
    PID: '65304',
    STAT: 'S+',
    COMM: '/usr/local/Cellar/node/15.5.1/bin/node'
  }
]
`

**Comment by UncleSamSwiss** [comment] 2021-03-15 10:34
Created the following issue: https://github.com/indexzero/ps-tree/issues/48

**Comment by UncleSamSwiss** [comment] 2021-03-15 10:45
@marwin79 Can you please verify the issue is fixed on MacOS?

**Closed** 2021-03-15 10:45 UTC
